get balance info implementation
xm-online/xm-ms-balance pull request #105
Opened 2023-03-28 11:12 UTC by illiaredko

get balance info implementation to master

2023-03-29 07:01 UTC, RomanTeren requested changes

2023-03-29 07:01 UTC, RomanTeren commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +        log.error("No logic for field: {}", field);
log.warn

2023-03-29 07:01 UTC, RomanTeren commented on src/main/java/com/icthh/xm/ms/balance/web/rest/BalanceResource.java
> +     * GET  /balances/:id/info : get the "id" balance.
... : get info about balance.

2023-03-29 07:01 UTC, RomanTeren commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$EXPIRED_AMOUNT.groovy
> +        log.debug("ExpiredAmount: execute: balanceDTO: {}", balanceDTO)
I guess, that default logback config includes class name, please update all similar log messages to 

```groovy
log.debug("execute: balanceDTO: {}", balanceDTO)
```

2023-03-29 07:01 UTC, RomanTeren commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$EXPIRE_BY_DATE.groovy
> +            expireByDateTime = Instant.parse(params?.find { it.key == "expireByDateTime" }?.value)
since it's a map, you can use implicit `Map.get()`: 
```groovy
expireByDateTime = Instant.parse(params.expireByDateTime)
```

2023-03-29 07:01 UTC, RomanTeren commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$SPENT_AMOUNT.groovy
> +        log.debug("SpentAmount: execute: balanceDTO: {}", balanceDTO)
remove class name from logs

2023-03-29 07:01 UTC, RomanTeren commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$FUTURE_AMOUNT.groovy
> +        log.debug("FutureAmount: execute: balanceDTO: {}", balanceDTO)
remove class name from logs

2023-03-29 09:13 UTC, illiaredko commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +        log.error("No logic for field: {}", field);
done

2023-03-29 09:13 UTC, illiaredko commented on src/main/java/com/icthh/xm/ms/balance/web/rest/BalanceResource.java
> +     * GET  /balances/:id/info : get the "id" balance.
done

2023-03-29 09:13 UTC, illiaredko commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$EXPIRED_AMOUNT.groovy
> +        log.debug("ExpiredAmount: execute: balanceDTO: {}", balanceDTO)
done

2023-03-29 09:13 UTC, illiaredko commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$EXPIRE_BY_DATE.groovy
> +            expireByDateTime = Instant.parse(params?.find { it.key == "expireByDateTime" }?.value)
done

2023-03-29 09:13 UTC, illiaredko commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$SPENT_AMOUNT.groovy
> +        log.debug("SpentAmount: execute: balanceDTO: {}", balanceDTO)
done

2023-03-29 09:13 UTC, illiaredko commented on src/main/resources/lep/default/service/ExtendBalanceInfo$$FUTURE_AMOUNT.groovy
> +        log.debug("FutureAmount: execute: balanceDTO: {}", balanceDTO)
done

2023-03-29 11:31 UTC, RomanTeren approved these changes

2023-03-30 07:30 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +    private List<String> splitToList(String fields) {
pls move this method to utils class (or use existing utils class)

2023-03-30 07:32 UTC, sergeysenja1992 approved these changes

2023-03-30 07:32 UTC, merged