Charge as many as possible feature
xm-online/xm-ms-balance pull request #85
Opened 2021-11-23 08:27 UTC by VovaViter

2021-11-23 09:09 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +            Metadata.of(chargingRequest.getMetadata()), applyDate, balance, true, chargingRequest.getAmount(), CHARGING);
2 и предпоследний параметр одинаковый?

2021-11-23 09:09 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +        BalanceChangeEvent eventFrom = createBalanceChangeEvent(operationUuid, amount, metadata, applyDate, sourceBalance, true, amount, TRANSFER_FROM);
2 и предпоследний параметр одинаковый?

2021-11-23 09:11 UTC, VovaViter commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +        BalanceChangeEvent eventFrom = createBalanceChangeEvent(operationUuid, amount, metadata, applyDate, sourceBalance, true, amount, TRANSFER_FROM);
да, обработка внутри идет потом если включен снять все

2021-11-23 09:11 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +                                       Page<Pocket> pockets, BalanceChangeEvent changeEvent, BalanceSpec.BalanceTypeSpec balanceSpec, Balance balance) {
import BalanceTypeSpec

2021-11-23 13:59 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +        BalanceChangeEventDto balanceChangeEventDto = returnExistBalanceChangeEventDto(existBalanceChangeEvents, false);
add overload method like returnExistsBalanceCHangeEventDtoWithPocketHistory

2021-11-23 14:03 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +                                                        BigDecimal amountTotal, OperationType transferTo) {
not needed parameters

2021-11-23 14:05 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +            changeEvent.addPocketChangeEvent(
pls check formatter max line size

2021-11-23 14:09 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +            BalanceTypeSpec balanceTypeSpec = balanceSpecService.getBalanceSpec(balance.getTypeKey());
duplicate code

2021-11-23 14:19 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +        AllowNegative allowNegative = balanceSpec.getAllowNegative();
extract to method

2021-11-23 14:20 UTC, sergeysenja1992 commented on src/main/java/com/icthh/xm/ms/balance/service/BalanceService.java
> +            }
extract method

2021-11-24 09:34 UTC, sergeysenja1992 approved these changes

2021-11-24 09:42 UTC, dtsarenko approved these changes

2021-11-24 10:35 UTC, sergeysenja1992 requested changes
Move allowChargeAsManyAsHave from spec to charge request

2021-11-24 11:42 UTC, sergeysenja1992 approved these changes

2021-11-24 12:42 UTC, merged